//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;

public class Attack: CardForm
{
    public Attack(Card.CardSuit suit, Card.CardNumber number, Card.CardState state, Player owner, Game g)
        : base(new Card(Card.CardType.Basic, "ATTACK", "attack1", "Used to attack one player.",
        suit, number, state, owner),g)
    {

    }

    void Start()
    {
        //Card atkCard = new Card(Card.CardType.Basic, "ATTACK", "attack1", "Used to attack one player.", 
        //    Card.CardSuit.Heart, Card.CardNumber.Ace, Card.CardState.Hand, null);
        ////this.name = atkCard.CardID.ToString();
        //this.Form = new CardForm(atkCard, 0, 0, 50, 70);
        //this.Form.OnClick += OnMouseClick;
        //this.Form.OnMouseMove += OnMouseMove;
        //this.Form.OnMouseEnter += OnMouseEnter;
        //this.Form.OnMouseLeave += OnMouseLeave;
    }

    public void PerformAttack()
    {
        Outline border = game.playerPanel6.GetComponent<Outline>();
        border.enabled = false;
        EventTrigger et = game.playerPanel6.GetComponent<EventTrigger>();
        et.delegates = null;
        GameObject tempPanel = GameObject.Find("Use Card Panel");
        Vector3 position = tempPanel.transform.localPosition;
        Action action = delegate()
        {
            this.Form.UpdateLastInteract();
            this.Form.Owner = null;
            this.Form.FaceUp = true;
            this.Form.CardData.State = Card.CardState.Piles;
            this.Form.State = Card.CardState.Piles;
            RefreshHand(game.myPlayer);
        };
        this.Form.Move(new Vector2(position.x, position.y), MoveSpeed, action);

        Player player = game.playerPanel6.GetComponent<Player>();
        player.CurrentHealth -= 1;
    }

    public override void UseCard()
    {
        
        Outline border = game.playerPanel6.GetComponent<Outline>();
        border.enabled = true;
        EventTrigger et = game.playerPanel6.GetComponent<EventTrigger>();
        EventTrigger.TriggerEvent trigger = new EventTrigger.TriggerEvent();
        EventTrigger.Entry entry = new EventTrigger.Entry();
        entry.eventID = EventTriggerType.PointerClick;
        entry.callback.AddListener((eventData) => { PerformAttack(); });
        et.delegates = new System.Collections.Generic.List<EventTrigger.Entry>();
        et.delegates.Add(entry);
        base.UseCard();
    }


}


