//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;

public class Dodge : CardForm
{
    public Dodge(Card.CardSuit suit, Card.CardNumber number, Card.CardState state, Player owner, Game g)
        : base(new Card(Card.CardType.Basic, "DODGE", "Dodge", "Used to dodge from an attack.",
        suit, number, state, owner),g)
    {

    }

    public void PerformDodge()
    {
        Player attacking = this.Form.Owner.targetPlayer;
        Player source = this.Form.Owner;
        this.mainAction = delegate()
        {
            if (attacking.EndAttack != null) attacking.EndAttack.Invoke(0, attacking, source);
            if (source.EndAttack != null) source.EndAttack.Invoke(0, attacking, source);
            game.PilesCollect();
        };
    }

    public override void UseCard()
    {
        PerformDodge();
        base.UseCard();
    }
}

