//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Attack: CardForm
{
    public Attack(Card.CardSuit suit, Card.CardNumber number, Card.CardState state, Player owner, Game g)
        : base(new Card(Card.CardType.Basic, "ATTACK", "attack1", "Used to attack one player.",
        suit, number, state, owner),g)
    {

    }

    void Start()
    {
        //Card atkCard = new Card(Card.CardType.Basic, "ATTACK", "attack1", "Used to attack one player.", 
        //    Card.CardSuit.Heart, Card.CardNumber.Ace, Card.CardState.Hand, null);
        ////this.name = atkCard.CardID.ToString();
        //this.Form = new CardForm(atkCard, 0, 0, 50, 70);
        //this.Form.OnClick += OnMouseClick;
        //this.Form.OnMouseMove += OnMouseMove;
        //this.Form.OnMouseEnter += OnMouseEnter;
        //this.Form.OnMouseLeave += OnMouseLeave;
    }

    public void PerformAttack()
    {
        
    }
}


