//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class Attack: MonoBehaviour
{
    public CardForm Form;
    void Start()
    {
        //this.CardData = new Card(global::Card.CardType.Basic, "ATTACK", asset,
        //    "Used for attack any other player", suit, number, state, owner);
        Card atkCard = new Card(Card.CardType.Basic, "ATTACK", "attack1", "Used to attack one player.", 
            Card.CardSuit.Heart, Card.CardNumber.Ace, Card.CardState.Hand, null);
        this.name = atkCard.CardID.ToString();
        this.Form = new CardForm(atkCard, 0, 0, 50, 70);
        //Form.onClick += Form_onClick;
    }

    void OnMouseDown()
    {
        Form.Height = 500;
        Form.Width = 300;
        //Form.Move(new Vector2(-100, -200), 5f, null);
    }

    void Update()
    {
        if(Form.Visible)Form.Update();
    }
}


