//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class Attack: Card
{
	public Attack (string name, string asset, string description,
	                  CardSuit suit, CardNumber number, CardState state, Player owner): 
		base (Card.CardType.Basic, name, asset, description, suit, number, state, owner)
	{
	}

	public override void UseCard ()
	{
		base.UseCard ();
	}

	public override void Discard ()
	{
		base.Discard ();
	}

	public override void Exchange ()
	{
		base.Exchange ();
	}
}


