//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

[Serializable]
public class Card
{
	public enum CardNumber
	{
		None = 0,
		Ace = 1,
		Two = 2,
		Three = 3,
		Four = 4,
		Five = 5,
		Six = 6,
		Seven = 7,
		Eight = 8,
		Nine = 9,
		Ten = 10,
		Jack = 11,
		Queen = 12,
		King =13,
		Joker = 0,
	}

	public enum CardSuit
	{
		None = 0,
		Spade = 1,
		Club = 2,
		Diamond = 3,
		Heart = 4,
	}

	public enum CardType
	{
		Tool = 0,
		Weapon = 1,
		Vehicle = 2,
		Basic = 3,
		Armor = 4,

	}

	public enum CardState
	{
		None = 0,
		Hand = 1,
		Equipment = 2,
		PendingDelay = 3,
		OnCharacter1 = 4,
		OnCharacter2 = 5,
        Piles = 6,
	}

	public string Name;
	public string Asset;
	public string Description;
	public CardSuit Suit;
	public CardNumber Number;
	public CardType Type;
	public CardState State;
	public Player Owner;
	public Guid CardID;

	public Card (CardType type, string name, string asset, string description,
		            CardSuit suit, CardNumber number, CardState state, Player owner)
	{
		this.Type = type;
		this.Name = name;
		this.Asset = asset;
		this.Description = description;
		this.Suit = suit;
		this.Number = number;
		this.State = state;
		this.Owner = owner;
		CardID = Guid.NewGuid();
	}

	public virtual void UseCard ()
	{	
	}
		
	public virtual void Discard ()
	{
	}

	public virtual void Exchange()
	{
	}
}


