//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using UnityEngine.UI;
using UnityEngine.EventSystems;

public class CardController
{
    #region Variable Declaration
    public Card CardData;
    public Card.CardState State = Card.CardState.None;
    public Player Owner = null;
    public DateTime LastInteract = DateTime.Now;
    public Texture2D frontTexture, backTexture;
    Vector2 position= new Vector2(0,0);
    float width = 50;
    float height = 70;
    GameObject go;    
    NeoButton button;
    public bool Enable = true;
    public bool Visible = true;
    Vector2 newPosition = Vector2.zero;
    float MoveSpeed = 0;
    Action action;
    public Rigidbody2D RigidBody;
    public RectTransform RectTrans;
    public float Order = 0.5f;
    public int Sorting = 1;
    public Outline Border;
    public Color HighlightColor;
    private bool hasBorder = false;
    private bool active;
    public Sprite MainSprite;
    public Sprite BackSprite;
    public bool FaceUp = false;
    public GameObject Suit, Number;
    Text suitText, numberText;
    RectTransform suitRt, numberRt;

    public delegate void UpdateDelegate();
    public UpdateDelegate FormsUpdate = null;
    public delegate void EventDelegate();
    public EventDelegate OnClick = null;
    public EventDelegate OnMouseUp = null;
    public EventDelegate OnMouseDown = null;
    public EventDelegate OnMouseEnter = null;
    public EventDelegate OnMouseLeave = null;
    public EventDelegate OnMouseMove = null;

    BoxCollider2D Collider;
    EventTrigger ev;
    #endregion

    #region Properties
    public GameObject gameObject
    {
        get { return go; }
        set { go = value; }
    }

    public bool Active
    {
        get { return active; }
        set 
        { 
            active = value;
            
        }
    }

    public bool HasBorder
    {
        get { return hasBorder; }
        set 
        { 
            hasBorder = value; 
            if(hasBorder)
            {
                Border.effectDistance = new Vector2(4, -4);
                
            }
            else
            {
                Border.effectDistance = new Vector2(0, 0);
            }
        }
    }

    public NeoButton Button
    {
        get
        {
            return button;
        }
        set
        {
            button = value;
        }
    }

    public Vector2 Position
    {
        get
        {
            return position;
        }
        set
        {
            position = value;
        }
    }

    public float Width
    {
        get
        {
            return width;
        }
        set
        {
            float change = value - width;
            if (suitRt != null) suitRt.sizeDelta = new Vector2(suitRt.GetWidth() + change, suitRt.GetHeight());
            if (numberRt != null) numberRt.sizeDelta = new Vector2(numberRt.GetWidth() + change, numberRt.GetHeight());
            width = value;
        }
    }

    public float Height
    {
        get
        {
            return height;
        }
        set
        {
            float change = value - height;
            if(suitRt!=null)suitRt.sizeDelta = new Vector2(suitRt.GetWidth(), suitRt.GetHeight() + change);
            if (numberRt != null) numberRt.sizeDelta = new Vector2(numberRt.GetWidth(), numberRt.GetHeight() + change);
            height = value;
        }
    } 
    #endregion

    #region Function
    public void Move(Vector2 _newPos, float _speed, Action _action)
    {
        newPosition = _newPos;
        MoveSpeed = _speed;
        action = _action;
        this.FormsUpdate = null;
        this.FormsUpdate += this.Mover;
    }

    private void Mover()
    {
        Vector2 move_speed = (newPosition - Position);
        move_speed.Normalize();
        if (float.IsNaN(move_speed.x) || float.IsNaN(move_speed.y))
        {
            move_speed = Vector2.one;
        }
        float move_time = MoveSpeed * Time.deltaTime;
        //Debug.Log("X:" + newPosition.x);
        //Debug.Log("Y:" + newPosition.y);
        //float move_time = MoveSpeed;
        Vector2 move_distance = move_speed * move_time;
        //Console.WriteLine(move_speed.ToString());
        if ((Math.Abs(Position.x - newPosition.x) <= Math.Abs(move_distance.x))
            && (Math.Abs(Position.y - newPosition.y) <= Math.Abs(move_distance.y)))
        {
            this.Position = newPosition;
            //rb.MovePosition(newPosition);

            MoveSpeed = 0f;
            this.FormsUpdate -= this.Mover;
            if (action != null)
            {
                action.Invoke();
                action = null;
            }
            return;
        }
        float newX = this.Position.x + move_distance.x;
        float newY = this.Position.y + move_distance.y;
        this.Position = new Vector2(newX, newY);
        //rb.MovePosition(new Vector2(newX, newY));
    } 

    public void UpdateLastInteract()
    {
        this.LastInteract = DateTime.Now;
        this.gameObject.transform.SetAsLastSibling();
    }
    #endregion
    GameObject sample;
    #region Init & Update
    public CardController(Card _card, float x, float y, float width, float heigh)
    {
        sample = GameObject.Find("Test Object");
        if (sample != null)
        {
            RectTransform rect = sample.GetComponent<RectTransform>();
            Width = rect.GetSize().x;
            Height = rect.GetSize().y;
        }
        this.CardData = _card;
		frontTexture = Resources.Load ("Cards/" + CardData.Asset)  as Texture2D;
        Init();
		Position = new Vector2 (x, y);
		//Width = width;
        //Height = heigh;
        
        //Init();
    }

    public void Init()
    {
        backTexture = Resources.Load("Cards/Card Back") as Texture2D;
        MainSprite = Sprite.Create(frontTexture, new Rect(0, 0, frontTexture.width, frontTexture.height), new Vector2(0f, 0f));
        BackSprite = Sprite.Create(backTexture, new Rect(0, 0, backTexture.width, backTexture.height), new Vector2(0f, 0f));
        GameObject mainPanel = GameObject.Find("Main Panel");
        go = new GameObject(CardData.CardID.ToString());
        this.Sorting = mainPanel.transform.childCount + 1;
        go.transform.SetParent(mainPanel.transform);
        Collider = go.AddComponent<BoxCollider2D>();
        Collider.isTrigger = true;
        Collider.size = new Vector2(Width, Height);
        RectTrans = go.AddComponent<RectTransform>();
        RectTrans.sizeDelta = new Vector2(Width, Height);
        RectTrans.anchoredPosition = new Vector2(Position.x, Position.y);

        Border = go.AddComponent<Outline>();
        Border.useGraphicAlpha = false;
        HighlightColor = Color.blue;
        Border.effectColor = HighlightColor;
        Border.effectDistance = new Vector2(0, 0);

        //MainSprite.border.Set(3, 3, 3, 3);
        //BackSprite.border.Set(3, 3, 3, 3);
        cv = go.AddComponent<Image>();
        cv.sprite = BackSprite;
        //cv.type = Image.Type.Sliced;
        FaceUp = false;

        //GameObject suitSample = sample.transform.FindChild("Suit").gameObject;
        //RectTransform suitRtSample = suitSample.GetComponent<RectTransform>();

        //GameObject numberSample = sample.transform.FindChild("Number").gameObject;
        //RectTransform numberRtSample = suitSample.GetComponent<RectTransform>();

        Font font = Resources.GetBuiltinResource<Font>("Arial.ttf");

        Number = new GameObject("Number");
        Number.transform.SetParent(go.transform);
        numberText = Number.AddComponent<Text>();
        numberText.font = font;
        numberText.text = this.CardData.GetNumber();
        numberText.color = Color.red;
        numberText.resizeTextForBestFit = true;
        numberText.alignment = TextAnchor.MiddleCenter;
        numberRt = Number.GetComponent<RectTransform>();
        numberRt.sizeDelta = new Vector2(Width / 3, Width / 3);
        numberRt.anchoredPosition = new Vector2(-(Width / 2.7f), (Height / 2.7f));

        Suit = new GameObject("Suit");
        Suit.transform.SetParent(go.transform);
        suitText = Suit.AddComponent<Text>();
        suitText.font = font;
        suitText.text = this.CardData.GetSuit();
        if (suitText.text == "♥" || suitText.text == "♦") suitText.color = Color.red;
        else suitText.color = Color.black;
        suitText.resizeTextForBestFit = true;
        suitText.alignment = TextAnchor.MiddleCenter;
        suitRt = Suit.GetComponent<RectTransform>();
        suitRt.sizeDelta = new Vector2(Width / 3, Width / 3);
        suitRt.anchoredPosition = new Vector2(-(Width / 2.7f), (Height / 2.7f) - numberRt.GetHeight()/1.5f);


        Outline suitOL = Suit.AddComponent<Outline>();
        suitOL.useGraphicAlpha = false;
        if(suitText.color == Color.red)suitOL.effectColor = Color.black;
        else suitOL.effectColor = Color.white;
        suitOL.effectDistance = new Vector2(1, -1);

        Outline numberOL = Number.AddComponent<Outline>();
        numberOL.useGraphicAlpha = false;
        numberOL.effectColor = Color.white;
        numberOL.effectDistance = new Vector2(1, -1);

        RigidBody = go.AddComponent<Rigidbody2D>();
        RigidBody.gravityScale = 0;

        //this.Visible = false;
        this.Active = false;

        #region Event Registration
        EventTrigger eventTrigger = go.AddComponent<EventTrigger>();

        EventTrigger.TriggerEvent trigger = new EventTrigger.TriggerEvent();

        EventTrigger.Entry entry = new EventTrigger.Entry();
        entry.eventID = EventTriggerType.PointerClick;
        trigger.AddListener((eventData) => { onMouseClick(); });
        entry.callback = trigger;

        EventTrigger.Entry entry2 = new EventTrigger.Entry();
        entry2.eventID = EventTriggerType.PointerEnter;
        entry2.callback.AddListener((eventData) => { onMouseEnter(); });

        EventTrigger.Entry entry3 = new EventTrigger.Entry();
        entry3.eventID = EventTriggerType.PointerExit;
        entry3.callback.AddListener((eventData) => { onMouseLeave(); });

        EventTrigger.Entry entry4 = new EventTrigger.Entry();
        entry4.eventID = EventTriggerType.PointerExit;
        entry4.callback.AddListener((eventData) => { onMouseMove(); });

        EventTrigger.Entry entry5 = new EventTrigger.Entry();
        entry5.eventID = EventTriggerType.PointerExit;
        entry5.callback.AddListener((eventData) => { onMouseDown(); });

        EventTrigger.Entry entry6 = new EventTrigger.Entry();
        entry6.eventID = EventTriggerType.PointerExit;
        entry6.callback.AddListener((eventData) => { onMouseUp(); });

        eventTrigger.delegates = new System.Collections.Generic.List<EventTrigger.Entry>();
        eventTrigger.delegates.Add(entry);
        eventTrigger.delegates.Add(entry2);
        eventTrigger.delegates.Add(entry3);
        eventTrigger.delegates.Add(entry4);
        eventTrigger.delegates.Add(entry5);
        eventTrigger.delegates.Add(entry6); 
        #endregion

    }
    Image cv;
    public void Update()
    {
        if (RectTrans != null)
        {
            RectTrans.sizeDelta = new Vector2(Width, Height);
            RectTrans.anchoredPosition3D = new Vector3(Position.x, Position.y, Order);
        }
        if (Collider!=null)
        {
            if (Collider.size.x != this.width || Collider.size.y != this.height)
            {
                Collider.size = new Vector2(this.width, this.height);
            }
        }
        if (go.activeSelf != Active) go.SetActive(Active);
        if (FaceUp)
        {
            cv.sprite = MainSprite;
            Suit.SetActive(true);
            Number.SetActive(true);
        }
        else
        {
            cv.sprite = BackSprite;
            Suit.SetActive(false);
            Number.SetActive(false);
        }
        
        if (this.FormsUpdate != null)
        {
            this.FormsUpdate.Invoke();
        }
    } 
    #endregion

    #region Handler
    private void onMouseClick()
    {
        if (this.OnClick != null)
        {
            this.OnClick.Invoke();
        }
    }
    private void onMouseEnter()
    {
        if (this.OnMouseEnter != null)
        {
            this.OnMouseEnter.Invoke();
        }
    }
    private void onMouseLeave()
    {
        if (this.OnMouseLeave != null)
        {
            this.OnMouseLeave.Invoke();
        }
    }
    private void onMouseUp()
    {
        if (this.OnMouseUp != null)
        {
            this.OnMouseUp.Invoke();
        }
        
    }
    private void onMouseDown()
    {
        if (this.OnMouseDown != null)
        {
            this.OnMouseDown.Invoke();
        }
    }
    private void onMouseMove()
    {
        if (this.OnMouseMove != null)
        {
            this.OnMouseMove.Invoke();
        }
    }

    #endregion

}


