//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class Character
{
	private string name;
	private int maxHealth;
	private CharacterType type;
	private Character perfectMatch;
	private string asset;
	public Player Owner = null;

		#region MyRegion Property
	public Character PerfectMatch {
		get {
			return perfectMatch;
		}
		set {
			perfectMatch = value;
		}
	}

	public string Asset {
		get {
			return asset;
		}
		set {
			asset = value;
		}
	}

	public CharacterType Type {
		get {
			return type;
		}
		set {
			type = value;
		}
	}

	public int MaxHealth {
		get {
			return maxHealth;
		}
		set {
			maxHealth = value;
		}
	}

	public string Name {
		get {
			return name;
		}
		set {
			name = value;
		}
	}
		#endregion

	public enum CharacterType
	{
		Servant,
		Master,
		Human,
		Monster,
		Ruler,
		Boss,
	}

	public Character ()
	{
	}

	public Character (string _name, int _maxHealth, CharacterType _type, Character _perfectMatch, string _asset)
	{
		this.Name = _name;
		this.Type = _type;
		this.PerfectMatch = _perfectMatch;
		this.MaxHealth = _maxHealth;
		this.Asset = _asset;
	}

	public virtual void Ability1()
	{
	}
	public virtual void Ability2()
	{
	}
	public virtual void Ability3()
	{
	}
	public virtual void Ability4()
	{
	}
	public virtual void Ability5()
	{
	}
	public virtual void Ability6()
	{
	}
		
	public virtual void Attack(Guid cardID, Guid source, Guid target)
	{
		Command cm = new Command (CommandCode.Attack, cardID, source, target);
	}

	public virtual void Heal(int number, Guid source, Guid target)
	{
		Command cm = new Command (CommandCode.Heal, number, source, target);
	}
	
	public virtual void CausePhysicalDamage(int number, Guid source, Guid target)
	{
		Command cm = new Command (CommandCode.CauseMagicDamage, number, source, target);
	}

	public virtual void ReceivedPhysicalDamage(int number, Guid source, Guid target)
	{
		Command cm = new Command (CommandCode.ReceivedPhysicalDamage, number, source, target);
	}
	
	public virtual void CauseMagicDamage(int number, Guid source, Guid target)
	{
		Command cm = new Command (CommandCode.CauseMagicDamage, number, source, target);
	}

	public virtual void ReceivedMagicDamage(int number, Guid source, Guid target)
	{
		Command cm = new Command (CommandCode.ReceivedMagicDamage, number, source, target);
	}
	
	public virtual void LossOfHealth(int number, Guid source, Guid target)
	{
		Command cm = new Command (CommandCode.LossOfHealth, number, source, target);
	}
}

