//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class Player
{
	public string PlayerName = "";
	public string IpAdress = "";
	public bool Status = false;
	public Character Character1;
	public Character Character2;
	public Guid PlayerID;
	public int HandLimit = 0;
	public int CurrentHealth = 0;
	public double MaxHealth = 0;
	public int AttackingRange = 1;
	public int MinusDistance = 0;
	public int PlusDistance = 0;

	public enum PlayerTurn
	{
		Beginning = 0,
		Judgment = 1,
		Draw = 2,
		Action = 3,
		Discard = 4,
		End = 5,
		OutTurn = 6,
	}

	public Player (string name)
	{
		this.PlayerName = name;
		PlayerID = Guid.NewGuid ();
	}
}

