//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class Servant:Character
{
	public enum ServantClass
	{
		Berserker = 0,
		Assassin = 1,
		Saber = 2,
		Lancer = 3,
		Archer = 4,
		Saver = 5,
		Caster = 6,
		Rider = 7,
	}
	public ServantClass Class;
}


