//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

[Serializable]
public class Tool: Card
{
	public enum ToolType
	{
		TimeDelay = 0,
		NonTimeDelay = 1,
	}
	public ToolType Type = ToolType.TimeDelay;

	public Tool (string name, string asset, string description,
	             CardSuit suit, CardNumber number, CardState state, ToolType type, Player owner): 
		base (Card.CardType.Tool, name, asset, description, suit, number, state, owner)
	{
		this.Type = type;
	}

	public override void UseCard ()
	{
		base.UseCard ();
	}
	
	public override void Discard ()
	{
		base.Discard ();
	}
	
	public override void Exchange ()
	{
		base.Exchange ();
	}
}


