//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;

public class Tool : CardForm
{
	public enum ToolType
	{
		TimeDelay = 0,
		NonTimeDelay = 1,
	}
	public ToolType Type = ToolType.TimeDelay;
    private string p1;
    private string p2;
    private string p3;
    private Card.CardSuit suit;
    private Card.CardNumber number;
    private Card.CardType state;
    private ToolType toolType;
    private Player player;
    private Game gg;

	public Tool (string name, string asset, string ability, Card.CardSuit suit, 
        Card.CardNumber number, Card.CardState state, ToolType type, Player owner, Game g):
        base(new Card(Card.CardType.Tool, name, asset, ability, suit, number, state, owner), g)
	{
		this.Type = type;
        this.UseCondition += useCondition;
	}

    public virtual bool useCondition()
    {
        Player owner = this.Form.Owner;
        if (owner.actionState == Player.ActionState.Free)
        {
            return true;
        }
        else
        {
            return false;
        }
    }

	public override void UseCard ()
	{
		base.UseCard ();
	}

    public virtual void TimeDelayEffect()
    {
        
    }

    public virtual void NonTimeDelayEffect()
    {

    }
	
	public virtual void Exchange ()
	{
		
	}
}


