//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

[Serializable]
public class Vehicle: Card
{
	public enum VehicleType
	{
		Minus = 0,
		Plus = 1,
	}
	public VehicleType Type = VehicleType.Minus;

	public Vehicle (string name, string asset, string description,
	                CardSuit suit, CardNumber number, CardState state, VehicleType type, Player owner): 
		base (Card.CardType.Vehicle, name, asset, description, suit, number, state, owner)
	{
		this.Type = type;
	}

	public override void UseCard ()
	{
		base.UseCard ();
	}
		
	public override void Discard ()
	{
		base.Discard ();
	}
		
	public override void Exchange ()
	{
		base.Exchange ();
	}
}


