//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;

public class Weapon : CardForm
{
	public int Range = 0;

    public Weapon(string name, string asset, string ability, int range, Card.CardSuit suit, 
        Card.CardNumber number, Card.CardState state, Player owner, Game g)
        : base(new Card(Card.CardType.Weapon, name, asset, ability, suit, number, state, owner), g)
    {
		this.Range = range;
	}

    public override void Equipped()
    {
        this.Form.Owner.AttackingRange += Range;
    }

    public override void UnEquipped()
    {
        this.Form.Owner.AttackingRange -= Range;
        if (this.Form.Owner.AttackingRange < 1) this.Form.Owner.AttackingRange = 1;
    }

	public virtual void Ability()
    {
        
    }

    public override void UseCard()
    {
        EquipAnimation();
    }
}


