//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;

public class Attack: CardForm
{
    public Attack(Card.CardSuit suit, Card.CardNumber number, Card.CardState state, Player owner, Game g)
        : base(new Card(Card.CardType.Basic, "Physical ATTACK", "PhysicalAttack", "Used to attack one player with physical damage.",
        suit, number, state, owner),g)
    {

    }

    public override void UseCard()
    {
        //Set All Player within attacking become selectable
        Attack();
    }
}


